export * from './enums';
export * from './labels';

export const STORAGE_KEYS = {
  ADMIN_TOKEN: 'ef_admin_token',
  ADMIN_PROFILE: 'ef_admin_profile',
} as const;

export const QUERY_KEYS = {
  AUTH_ME: ['auth', 'me'] as const,
  DASHBOARD_METRICS: ['dashboard', 'metrics'] as const,
  DASHBOARD_ALERTS: ['dashboard', 'alerts'] as const,
  DASHBOARD_DAU_CHART: (days: number) => ['dashboard', 'dau', days] as const,
  DASHBOARD_REVENUE_CHART: (days: number) => ['dashboard', 'revenue', days] as const,
  USERS: (params?: unknown) => ['users', params] as const,
  USER_DETAIL: (userId: string | number) => ['users', userId] as const,
  REPORTS: (params?: unknown) => ['reports', params] as const,
  REPORT_DETAIL: (reportId: string | number) => ['reports', reportId] as const,
  PAYMENTS: (params?: unknown) => ['payments', params] as const,
  PAYMENT_DETAIL: (paymentId: string | number) => ['payments', paymentId] as const,
  PROFILE_REVIEWS: (params?: unknown) => ['profile-reviews', params] as const,
  NOTICES: (params?: unknown) => ['notices', params] as const,
  BAL_APPLIES: (params?: unknown) => ['bal-applies', params] as const,
  BAL_GAMES: (params?: unknown) => ['bal-games', params] as const,
  BAL_GAME_DETAIL: (uuid: string) => ['bal-games', uuid] as const,
  BAL_GAME_STATS: ['bal-games', 'stats'] as const,
  AUDIT_LOGS: (params?: unknown) => ['audit-logs', params] as const,
  SUSPENSION_LOGS: (params?: unknown) => ['suspension-logs', params] as const,
  SUSPENSION_LOG_DETAIL: (id: string | number) => ['suspension-logs', id] as const,
  POST_ITS: (params?: unknown) => ['post-its', params] as const,
  POST_IT_DETAIL: (uuid: string) => ['post-its', uuid] as const,
  FEEDBACKS: (params?: unknown) => ['feedbacks', params] as const,
  FEEDBACK_DETAIL: (id: string | number) => ['feedbacks', id] as const,
  BLOCKS: (params?: unknown) => ['blocks', params] as const,
  BANNED_WORDS: (params?: unknown) => ['banned-words', params] as const,
  PREMIUM_MEMBERS: (params?: unknown) => ['premium', params] as const,
  REVENUE_SUMMARY: (range?: unknown) => ['revenue', 'summary', range] as const,
  REVENUE_BY_METHOD: (range?: unknown) => ['revenue', 'method', range] as const,
  REVENUE_BY_PLAN: (range?: unknown) => ['revenue', 'plan', range] as const,
  REVENUE_DAILY_CHART: (days: number) => ['revenue', 'daily', days] as const,
  PAYMENT_DAILY_SUMMARY: (days: number) => ['payments', 'daily-summary', days] as const,
  MATCHING_FUNNEL: ['matching', 'funnel'] as const,
  MATCHING_DAILY: (days: number) => ['matching', 'daily', days] as const,
  MATCHING_WEIGHTS: ['matching', 'weights'] as const,
  ADMINS: (params?: unknown) => ['admins', params] as const,
  ADMIN_DETAIL: (id: string | number) => ['admins', id] as const,
  POLICIES: (params?: unknown) => ['policies', params] as const,
  POLICY_DETAIL: (uuid: string) => ['policies', uuid] as const,
  FAQS: (params?: unknown) => ['faqs', params] as const,
  FAQ_DETAIL: (id: string | number) => ['faqs', id] as const,
  SYSTEM_MESSAGES: (params?: unknown) => ['system-messages', params] as const,
  NOTICES_BE: (params?: unknown) => ['notices-be', params] as const,
  NOTICE_BE_DETAIL: (id: string | number) => ['notices-be', id] as const,
  BAL_APPLIES_BE: (params?: unknown) => ['bal-applies-be', params] as const,
  BAL_GAMES_BE: (params?: unknown) => ['bal-games-be', params] as const,
  BAL_GAME_BE_DETAIL: (id: string | number) => ['bal-games-be', id] as const,
  POST_ITS_BE: (params?: unknown) => ['post-its-be', params] as const,
  POST_IT_BE_DETAIL: (uuid: string) => ['post-its-be', uuid] as const,
  PUSHES: (params?: unknown) => ['pushes', params] as const,
  PUSH_DETAIL: (id: string | number) => ['pushes', id] as const,
} as const;
